### PR TITLE
Fix Dockerfile not exposing Ports and build E2E Integration Test for registry Pushing

### LINKED ISSUE #596: Ports don't get exposed in Dockerfile

### PR DESCRIPTION
**Pull request by c-mueller**
To Quote my commit message: 
```
The Kubernetes Plugin uses this CSAR for testing the Pushing capability
of the Kubernetes lifecycle.
The CSAR represents a Staticly linked linux binary that runs a HTTP
server on Port 8080 showing some system Information (Similar to the
        Docker Image 'tutum/hello-world')
The Source Code of the 'App' can be Found in the samples Repository
```

This test tries to transform the image, push it to a local registry, pull it from there (after removing the image localy) and running the image within docker.

This PR also resolves #596

### CODE REVIEW

File: server/src/integration/java/org/opentosca/toscana/plugins/kubernetes/model/KubernetesPushingGopherIT.java [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+            .hostConfig(hostConfig)
+            .image(EXPECTED_TAG).build();
+        String id = client.createContainer(config).id();
+        this.runningContainers.add(id);
+
+        client.startContainer(id);
+
+        Thread.sleep(5000);
+        OkHttpClient httpClient = new OkHttpClient();
+        Request request = new Request.Builder().url("http://127.0.0.1:17717/").get().build();
```
Comment (JensMueller2709) [inline server/src/integration/java/org/opentosca/toscana/plugins/kubernetes/model/KubernetesPushingGopherIT.java]: Consider to make the port `17717` as a constant. I already saw this port above

Comment (c-mueller) [reply server/src/integration/java/org/opentosca/toscana/plugins/kubernetes/model/KubernetesPushingGopherIT.java]: Had to make the port dynamic anyways.
